inherit_gem:
  rubocop-gp:
    - ./config/default.yml

AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/const_stricter/const_stricter_evaluate_spec.rb

RSpec/LeakyConstantDeclaration:
  Exclude:
    - spec/const_stricter/const_stricter_evaluate_spec.rb

Gp/SpecConstantAssignment:
  Exclude:
    - spec/const_stricter/const_stricter_evaluate_spec.rb

RSpec/DescribedClass:
  Exclude:
    - spec/const_stricter/const_stricter_evaluate_spec.rb
